# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and run tests across different versions of Node.js
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["Production"] # Use lowercase letters for branch names
  pull_request:
    branches: ["Production"] # Use lowercase letters for branch names

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Test across multiple Node.js versions
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: yarn install # Use 'yarn install' instead of 'yarn' for consistency and add '--frozen-lockfile' for deterministic builds
      - name: Build and test
        run: |
          yarn run build
          yarn test
      - name: Install TypeScript
        run: yarn add typescript
      - name: Build with TypeScript
        run: yarn run build
      - name: Start the app
        run: yarn run start
